using Lurnyx.Data.Models;
using static Lurnyx.Resources.Constants.Enums;

namespace Lurnyx.Data
{
    public static class TrainingSeeder
    {
        public static List<Training> Seed()
        {
            var now = DateTime.Parse("2025-07-10T12:55:00Z").ToUniversalTime();
            
            var trainings = new List<Training> {
          new Training {
              Id = 1,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-1-Programming%20Fundamentals%20with%20Python.jpg",
              Title = "Programming Fundamentals with Python",
              Description = "Start your coding journey with Python, one of the most beginner-friendly languages. This course covers basic syntax, data structures, and problem-solving techniques through hands-on exercises. By the end, you'll be able to write simple programs and understand core programming principles.",
              Difficulty = TrainingDifficulty.BEGINNER,
              IsFeatured = true,
              TrainingCategoryId = 1,
              ViewCount = 245,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 2,
              UpdatedBy = 2
          },
          new Training {
              Id = 2,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-2-Object-Oriented%20Java%20Programming.png",
              Title = "Object-Oriented Java Programming",
              Description = "Learn Java by exploring the core principles of object-oriented programming. This course includes classes, inheritance, interfaces, and abstraction through interactive coding examples.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = true,
              TrainingCategoryId = 1,
              ViewCount = 198,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 3,
              UpdatedBy = 3
          },
          new Training {
              Id = 3,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-3-Web%20Development%20Essentials.webp",
              Title = "Web Development Essentials",
              Description = "Discover how to build beautiful and responsive websites using HTML, CSS, and JavaScript. This course guides you through layout techniques, styling, DOM manipulation, and project-based learning.",
              Difficulty = TrainingDifficulty.BEGINNER,
              IsFeatured = true,
              TrainingCategoryId = 2,
              ViewCount = 312,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 4,
              UpdatedBy = 4
          },
          new Training {
              Id = 4,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-4-Introduction%20to%20ASP.NET%20Core.jpg",
              Title = "Introduction to ASP.NET Core",
              Description = "Build robust web applications using ASP.NET Core and the MVC architecture. This course covers routing, controllers, views, and working with databases through Entity Framework.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = true,
              TrainingCategoryId = 2,
              ViewCount = 175,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 2,
              UpdatedBy = 2
          },
          new Training {
              Id = 5,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-5-Data%20Analysis%20with%20Python%20&%20Pandas.jpg",
              Title = "Data Analysis with Python & Pandas",
              Description = "Dive into data analysis using Python's powerful libraries like pandas and NumPy. Learn how to manipulate, analyze, and visualize real datasets through practical exercises.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = true,
              TrainingCategoryId = 7,
              ViewCount = 204,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 3,
              UpdatedBy = 3
          },
          new Training {
              Id = 6,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-6-Mobile%20App%20Development%20with%20Flutter.webp",
              Title = "Mobile App Development with Flutter",
              Description = "Learn how to develop cross-platform mobile applications using Flutter and the Dart programming language. This course covers widget trees, layouts, navigation, and state management through hands-on projects and exercises.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = true,
              TrainingCategoryId = 15,
              ViewCount = 189,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 4,
              UpdatedBy = 4
          },
          new Training {
              Id = 7,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-7-Machine%20Learning%20Foundations.jpg",
              Title = "Machine Learning Foundations",
              Description = "Gain a beginner-friendly introduction to machine learning. Topics include supervised learning, model training, and evaluation using real-world datasets.",
              Difficulty = TrainingDifficulty.BEGINNER,
              IsFeatured = false,
              TrainingCategoryId = 7,
              ViewCount = 150,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 2,
              UpdatedBy = 2
          },
          new Training {
              Id = 8,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-8-Introduction%20to%20SQL%20&%20Databases.png",
              Title = "Introduction to SQL & Databases",
              Description = "Explore the fundamentals of database design and querying using SQL. This course walks you through data retrieval, joins, filtering, and table relationships.",
              Difficulty = TrainingDifficulty.BEGINNER,
              IsFeatured = false,
              TrainingCategoryId = 5,
              ViewCount = 137,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 3,
              UpdatedBy = 3
          },
          new Training {
              Id = 9,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-9-Introduction%20to%20Node%20js.png",
              Title = "Introduction to Node.js",
              Description = "Discover how to build scalable back-end applications using Node.js and Express. This course introduces asynchronous programming, RESTful APIs, and database integration with MongoDB.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 2,
              ViewCount = 162,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 4,
              UpdatedBy = 4
          },
          new Training {
              Id = 10,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-10-Git%20&%20Version%20Control%20Essentials.jpg",
              Title = "Git & Version Control Essentials",
              Description = "Master version control using Git and GitHub. Learn how to track changes, manage branches, resolve merge conflicts, and collaborate on codebases.",
              Difficulty = TrainingDifficulty.BEGINNER,
              IsFeatured = false,
              TrainingCategoryId = 1,
              ViewCount = 221,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 2,
              UpdatedBy = 2
          },
          new Training {
              Id = 11,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-11-Introduction%20to%20Reactjs.png",
              Title = "Introduction to React.js",
              Description = "Learn to build dynamic web interfaces with React. This course covers components, props, state, and React Hooks through engaging examples and hands-on labs.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = true,
              TrainingCategoryId = 2,
              ViewCount = 247,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 3,
              UpdatedBy = 3
          },
          new Training {
              Id = 12,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-12-DevOps%20Fundamentals.jpg",
              Title = "DevOps Fundamentals",
              Description = "Explore the key principles of DevOps and modern software delivery. This course covers CI/CD pipelines, Docker containers, infrastructure as code, and basic deployment practices.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 8,
              ViewCount = 132,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 4,
              UpdatedBy = 4
          },
          new Training {
              Id = 13,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-13-Fundamentals%20of%20UXUI%20Design.jpg",
              Title = "Fundamentals of UX/UI Design",
              Description = "Understand what makes a product user-friendly and visually appealing. This course introduces UX research, wireframing, design systems, and interactive prototyping using Figma and other tools.",
              Difficulty = TrainingDifficulty.BEGINNER,
              IsFeatured = false,
              TrainingCategoryId = 2,
              ViewCount = 148,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 2,
              UpdatedBy = 2
          },
          new Training {
              Id = 14,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-14-Cybersecurity%20Basics.jpg",
              Title = "Cybersecurity Basics",
              Description = "Learn the foundations of cybersecurity and how to protect digital assets. This course covers encryption, common threats, network vulnerabilities, and security best practices.",
              Difficulty = TrainingDifficulty.BEGINNER,
              IsFeatured = false,
              TrainingCategoryId = 3,
              ViewCount = 121,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 3,
              UpdatedBy = 3
          },
          new Training {
              Id = 15,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-15-Cloud%20Computing%20with%20AWS.jpg",
              Title = "Cloud Computing with AWS",
              Description = "Get started with Amazon Web Services (AWS) by learning key services such as EC2, S3, and RDS. This course walks you through deployment, storage, and networking basics using real-world use cases.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 6,
              ViewCount = 176,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 4,
              UpdatedBy = 4
          },
          new Training {
              Id = 16,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-16-Introduction%20to%20Programming.webp",
              Title = "Introduction to Programming",
              Description = "A beginner's guide to the world of programming. This course explores what programming is, how it works, and its impact on modern computing. Gain foundational knowledge to start writing basic code.",
              Difficulty = TrainingDifficulty.BEGINNER,
              IsFeatured = true,
              TrainingCategoryId = 1,
              ViewCount = 142,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 2,
              UpdatedBy = 2
          },
          new Training {
              Id = 17,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-17-Advanced%20Data%20Science.webp",
              Title = "Advanced Data Science",
              Description = "Build upon your data science skills with topics like machine learning pipelines, model tuning, and deep learning. This course is ideal for learners with prior data experience.",
              Difficulty = TrainingDifficulty.ADVANCED,
              IsFeatured = false,
              TrainingCategoryId = 7,
              ViewCount = 131,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 3,
              UpdatedBy = 3
          },
          new Training {
              Id = 18,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-18-Cross-Platform%20Mobile%20Development.jpg",
              Title = "Cross-Platform Mobile Development",
              Description = "Learn the fundamentals of developing apps that run across iOS and Android using tools like Flutter and React Native.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 15,
              ViewCount = 168,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 4,
              UpdatedBy = 4
          },
          new Training {
              Id = 19,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-19-Practical%20Machine%20Learning%20with%20Python.jpg",
              Title = "Practical Machine Learning with Python",
              Description = "Apply machine learning principles using Python. Emphasis on hands-on implementation of classification, clustering, and regression techniques using scikit-learn.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 7,
              ViewCount = 156,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 2,
              UpdatedBy = 2
          },
          new Training {
              Id = 20,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-20-Web%20Accessibility%20and%20SEO%20Fundamentals.png",
              Title = "Web Accessibility and SEO Fundamentals",
              Description = "Learn how to build inclusive, discoverable websites. This course covers WCAG compliance, screen reader support, semantic HTML, and on-page SEO best practices.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 2,
              ViewCount = 128,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 3,
              UpdatedBy = 3
          },
          new Training {
              Id = 21,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-21-Algorithms%20and%20Problem%20Solving.jpg",
              Title = "Algorithms and Problem Solving",
              Description = "Strengthen your logical thinking and coding efficiency through foundational algorithms and data structures. This course covers sorting, searching, recursion, and problem-solving strategies commonly used in software engineering. Ideal for those preparing for technical interviews and competitive programming challenges.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 4,
              ViewCount = 110,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 4,
              UpdatedBy = 4
          },
          new Training {
              Id = 22,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-22-Relational%20Database%20Systems.png",
              Title = "Relational Database Systems",
              Description = "Learn how relational databases manage and store data efficiently. This course introduces schema design, normalization, indexing, and SQL querying techniques. You'll gain practical skills to design, query, and optimize relational databases in real-world applications.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 5,
              ViewCount = 98,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 2,
              UpdatedBy = 2
          },
          new Training {
              Id = 23,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-23-Agile%20Software%20Development.jpg",
              Title = "Agile Software Development",
              Description = "Explore industry-standard software engineering practices that improve development workflows. This course covers Agile methodologies, Scrum, version control using Git, unit testing, and continuous integration pipelines. Perfect for developers aiming to enhance team collaboration and code quality.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 8,
              ViewCount = 123,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 3,
              UpdatedBy = 3
          },
          new Training {
              Id = 24,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-24-Introduction%20to%20Computer%20Networks.jpg",
              Title = "Introduction to Computer Networks",
              Description = "Understand the principles behind computer networks and how devices communicate over the internet. Topics include network models, IP addressing, protocols like TCP/IP, routing, and basic network troubleshooting. A great starting point for careers in IT and systems administration.",
              Difficulty = TrainingDifficulty.BEGINNER,
              IsFeatured = false,
              TrainingCategoryId = 9,
              ViewCount = 115,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 4,
              UpdatedBy = 4
          },
          new Training {
              Id = 25,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-25-IoT%20and%20Embedded%20Systems.jpg",
              Title = "IoT and Embedded Systems",
              Description = "Delve into the world of smart devices and real-time embedded computing. Learn about microcontrollers, sensors, and communication protocols used in the Internet of Things (IoT). This course offers hands-on experience in building connected systems for smart environments.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 10,
              ViewCount = 89,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 2,
              UpdatedBy = 2
          },
          new Training {
              Id = 26,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-26-Game%20Development%20with%20Unity.jpg",
              Title = "Game Development with Unity",
              Description = "Learn how to create interactive 2D and 3D games using Unity, one of the most popular game engines. This course covers scripting in C#, game physics, animation, and user interface design. Ideal for aspiring game developers who want to bring their ideas to life.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 11,
              ViewCount = 142,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 3,
              UpdatedBy = 3
          },
          new Training {
              Id = 27,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-27-Quantum%20Computing%20Basics.jpg",
              Title = "Quantum Computing Basics",
              Description = "Explore the revolutionary concepts behind quantum computing. This course introduces qubits, entanglement, quantum gates, and basic quantum algorithms using tools like Qiskit or Q#. No prior experience in quantum physics is required—just curiosity and a willingness to learn.",
              Difficulty = TrainingDifficulty.ADVANCED,
              IsFeatured = false,
              TrainingCategoryId = 12,
              ViewCount = 67,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 4,
              UpdatedBy = 4
          },
          new Training {
              Id = 28,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-28-Blockchain%20App%20Development.jpg",
              Title = "Blockchain App Development",
              Description = "Build decentralized applications using blockchain technologies such as Ethereum. Learn how smart contracts work, how to write them using Solidity, and how blockchain networks handle consensus and transactions. Designed for developers interested in Web3 and decentralized platforms.",
              Difficulty = TrainingDifficulty.ADVANCED,
              IsFeatured = false,
              TrainingCategoryId = 13,
              ViewCount = 103,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 2,
              UpdatedBy = 2
          },
          new Training {
              Id = 29,
              CoverImageUrl = "https://obsdbfqybmsyxlhkkxhc.supabase.co/storage/v1/object/public/lurnyx-images/training-cover-images/2025-07/08/training-29-AR%20VR%20Development%20Fundamentals.jpeg",
              Title = "AR/VR Development Fundamentals",
              Description = "Enter the world of immersive technology through Augmented and Virtual Reality development. This course explores spatial computing, Unity XR toolkit, and user interaction in 3D environments. By the end, you'll be equipped to build engaging AR/VR experiences.",
              Difficulty = TrainingDifficulty.INTERMEDIATE,
              IsFeatured = false,
              TrainingCategoryId = 14,
              ViewCount = 95,
              CreatedAt = now,
              UpdatedAt = now,
              CreatedBy = 3,
              UpdatedBy = 3
          }
      };
            return trainings;
        }
    }
}
