//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lurnyx.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lurnyx.Resources.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve public URL for the uploaded file..
        /// </summary>
        public static string FailedToGetPublicUrl {
            get {
                return ResourceManager.GetString("FailedToGetPublicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File cannot be empty..
        /// </summary>
        public static string FileCannotBeEmpty {
            get {
                return ResourceManager.GetString("FileCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exceeds the size limit of {0}MB..
        /// </summary>
        public static string FileExceedsSizeLimit {
            get {
                return ResourceManager.GetString("FileExceedsSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed..
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again later!.
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password or email..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file..
        /// </summary>
        public static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension..
        /// </summary>
        public static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image..
        /// </summary>
        public static string InvalidImage {
            get {
                return ResourceManager.GetString("InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MIME type..
        /// </summary>
        public static string InvalidMimeType {
            get {
                return ResourceManager.GetString("InvalidMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid token is required to reset your password.
        /// </summary>
        public static string MissingToken {
            get {
                return ResourceManager.GetString("MissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password is incorrect. Please try again..
        /// </summary>
        public static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating does not exists..
        /// </summary>
        public static string RatingDoesNotExist {
            get {
                return ResourceManager.GetString("RatingDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error occured!.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic does not exist..
        /// </summary>
        public static string TopicDoesNotExist {
            get {
                return ResourceManager.GetString("TopicDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic with this title already exists..
        /// </summary>
        public static string TopicExist {
            get {
                return ResourceManager.GetString("TopicExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training category does not exist..
        /// </summary>
        public static string TrainingCategoryDoesNotExist {
            get {
                return ResourceManager.GetString("TrainingCategoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training name already exists!.
        /// </summary>
        public static string TrainingCategoryExist {
            get {
                return ResourceManager.GetString("TrainingCategoryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training with this title already exists..
        /// </summary>
        public static string TrainingDoesExist {
            get {
                return ResourceManager.GetString("TrainingDoesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training does not exist.
        /// </summary>
        public static string TrainingDoesNotExist {
            get {
                return ResourceManager.GetString("TrainingDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No training progress found for this user and training..
        /// </summary>
        public static string TrainingProgressDoesNotExist {
            get {
                return ResourceManager.GetString("TrainingProgressDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exists!.
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email already exists!.
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authenticated.
        /// </summary>
        public static string UserNotAuth {
            get {
                return ResourceManager.GetString("UserNotAuth", resourceCulture);
            }
        }
    }
}
